/* Eskişehir Bike Shop
 * Supabase client configuration goes in CONFIG below.
 * Never put a Supabase service_role key in this file.
 */
const SUPABASE_URL = "PASTE_YOUR_SUPABASE_PROJECT_URL_HERE";
const SUPABASE_ANON_KEY = "PASTE_YOUR_SUPABASE_ANON_KEY_HERE";
const CONFIGURED = SUPABASE_URL.startsWith("https://") && !SUPABASE_URL.includes("PASTE_") && !SUPABASE_ANON_KEY.includes("PASTE_");
const db = CONFIGURED ? window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null;

const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const state = { user:null, profile:null, listings:[], favorites:new Set(), authMode:"login", category:"", search:"", sort:"new", selectedListing:null };
const formatPrice = n => new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:0}).format(Number(n)||0);
const esc = s => String(s ?? "").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const initial = s => (s||"U").trim().charAt(0).toUpperCase();
function toast(message){const el=$("#toast");el.textContent=message;el.classList.remove("hidden");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.add("hidden"),3300)}
function showModal(id){$("#"+id).classList.remove("hidden");document.body.style.overflow="hidden"}
function closeModal(id){$("#"+id).classList.add("hidden");if(!$$(".modal-backdrop:not(.hidden)").length)document.body.style.overflow=""}
function message(id,text,error=false){const el=$("#"+id);el.textContent=text;el.classList.toggle("error",error)}
function placeholder(category=""){if((category||"").includes("Bisiklet"))return "🚲";if((category||"").includes("Maşa"))return "⌁";if((category||"").includes("Jant"))return "◉";if((category||"").includes("Vites"))return "⚙";if((category||"").includes("Fren"))return "⦿";if((category||"").includes("Pedal"))return "✣";if((category||"").includes("Lastik"))return "◌";return "▱"}
function demoListings(){return []}
async function refreshSession(){
  if(!db){render();$("#statusMessage").textContent="Ön izleme modu: Gerçek üyelik ve ilanlar için Supabase bağlantını app.js dosyasına ekle.";return}
  const {data:{session}}=await db.auth.getSession();state.user=session?.user||null;
  if(state.user){const {data}=await db.from("profiles").select("*").eq("id",state.user.id).maybeSingle();state.profile=data||null;await loadFavorites()}
  else {state.profile=null;state.favorites.clear()}
  updateHeader();await loadListings();
}
function updateHeader(){
  const logged=!!state.user;$("#loginOpen").classList.toggle("hidden",logged);$("#profileOpen").classList.toggle("hidden",!logged);
  $("#profileOpen").textContent=initial(state.profile?.username||state.user?.email);$("#postOpen").textContent=logged?"＋ İlan ver":"＋ İlan ver";
}
async function loadListings(){
  if(!db){state.listings=demoListings();render();return}
  $("#statusMessage").textContent="İlanlar yükleniyor...";
  const {data,error}=await db.from("listings").select("*, profiles(username, district)").eq("status","approved").order("created_at",{ascending:false}).limit(100);
  if(error){$("#statusMessage").textContent="İlanlar yüklenemedi. Supabase SQL kurulumunu ve RLS politikalarını kontrol et.";console.error(error);state.listings=[]}
  else {state.listings=data||[];$("#statusMessage").textContent=state.listings.length?`${state.listings.length} ilan listeleniyor`:"Henüz onaylanmış ilan yok. İlk ilanı sen ekle!"}
  render();
}
async function loadFavorites(){
  if(!db||!state.user)return;
  const {data,error}=await db.from("favorites").select("listing_id").eq("user_id",state.user.id);
  if(!error)state.favorites=new Set((data||[]).map(x=>x.listing_id));
}
function filteredListings(){
  let arr=state.listings.filter(x=>(!state.category||x.category===state.category)&&(!state.search||`${x.title} ${x.description} ${x.category} ${x.district||""}`.toLocaleLowerCase("tr").includes(state.search.toLocaleLowerCase("tr"))));
  if(state.sort==="low")arr.sort((a,b)=>a.price-b.price);else if(state.sort==="high")arr.sort((a,b)=>b.price-a.price);else arr.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));return arr;
}
function render(){
  const arr=filteredListings();$("#listingGrid").innerHTML=arr.map(x=>`<article class="listing-card" data-open-listing="${x.id}"><div class="listing-image">${x.image_url?`<img src="${esc(x.image_url)}" alt="${esc(x.title)}" loading="lazy">`:`<div class="listing-placeholder">${placeholder(x.category)}</div>`}<span class="condition-tag">${esc(x.condition||"İkinci el")}</span><button class="favorite-btn ${state.favorites.has(x.id)?"favorited":""}" data-favorite="${x.id}" aria-label="Favoriye ekle">${state.favorites.has(x.id)?"♥":"♡"}</button></div><div class="listing-body"><div class="listing-category">${esc(x.category)}</div><h3>${esc(x.title)}</h3><div class="listing-price">${formatPrice(x.price)}</div><div class="listing-meta"><span>⌖ ${esc(x.district||"Eskişehir")}</span><span>${timeAgo(x.created_at)}</span></div><div class="seller-line"><span class="seller-dot">${initial(x.profiles?.username)}</span><span>${esc(x.profiles?.username||"ESB Shop üyesi")}</span></div></div></article>`).join("");
  $("#emptyState").classList.toggle("hidden",arr.length>0);$("#statusMessage").classList.toggle("hidden",arr.length>0);$$(".category-card").forEach(c=>c.classList.toggle("selected",c.dataset.category===state.category));
}
function timeAgo(date){if(!date)return "Yeni";const mins=Math.max(0,Math.floor((Date.now()-new Date(date).getTime())/60000));if(mins<60)return mins<2?"Az önce":`${mins} dk önce`;if(mins<1440)return `${Math.floor(mins/60)} sa önce`;return `${Math.floor(mins/1440)} gün önce`}
function requireAuth(){if(!state.user){openAuth("login");toast("Devam etmek için giriş yapmalısın.");return false}return true}
function openAuth(mode="login"){state.authMode=mode;updateAuthMode();showModal("authModal")}
function updateAuthMode(){$$("[data-auth-mode]").forEach(b=>b.classList.toggle("active",b.dataset.authMode===state.authMode));$("#authTitle").textContent=state.authMode==="login"?"Tekrar hoş geldin":"Topluluğa katıl";$("#authDescription").textContent=state.authMode==="login"?"İlan vermek ve favorilerini kaydetmek için giriş yap.":"Ücretsiz hesabını oluştur ve ilanlarını yönet.";$("#usernameField").classList.toggle("hidden",state.authMode!=="signup");$("#authUsername").required=state.authMode==="signup";$("#authSubmit").textContent=state.authMode==="login"?"Giriş yap":"Hesap oluştur";$("#authPassword").autocomplete=state.authMode==="login"?"current-password":"new-password";message("authMessage","")}
async function authSubmit(e){e.preventDefault();if(!db){message("authMessage","Önce Supabase URL ve anon key bilgilerini app.js dosyasına ekle.",true);return}const email=$("#authEmail").value.trim(),password=$("#authPassword").value,username=$("#authUsername").value.trim();const btn=$("#authSubmit");btn.disabled=true;btn.textContent="İşleniyor...";
  try{if(state.authMode==="signup"){if(!/^[a-zA-Z0-9_.-]{3,24}$/.test(username)){message("authMessage","Kullanıcı adı 3-24 karakter olmalı; harf, rakam, nokta, tire ve alt çizgi kullan.",true);return}const {data,error}=await db.auth.signUp({email,password,options:{data:{username}}});if(error)throw error;if(data.session){toast("Hesabın oluşturuldu!");closeModal("authModal");await refreshSession()}else message("authMessage","Kayıt alındı. E-postana gelen doğrulama bağlantısına tıkla, sonra giriş yap.")}else{const {error}=await db.auth.signInWithPassword({email,password});if(error)throw error;closeModal("authModal");toast("Giriş başarılı!");await refreshSession()}}
  catch(err){message("authMessage",friendlyError(err.message),true)}finally{btn.disabled=false;btn.textContent=state.authMode==="login"?"Giriş yap":"Hesap oluştur"}}
function friendlyError(s){if(/Invalid login credentials/i.test(s))return "E-posta veya şifre hatalı.";if(/already registered/i.test(s))return "Bu e-posta ile bir hesap zaten var.";if(/rate limit/i.test(s))return "Çok fazla deneme yapıldı. Biraz bekleyip tekrar dene.";return s||"Bir hata oluştu."}
async function toggleFavorite(id){if(!requireAuth())return;const exists=state.favorites.has(id);if(exists){const {error}=await db.from("favorites").delete().eq("user_id",state.user.id).eq("listing_id",id);if(error){toast("Favori kaldırılamadı.");return}state.favorites.delete(id)}else{const {error}=await db.from("favorites").insert({user_id:state.user.id,listing_id:id});if(error){toast("Favori eklenemedi.");return}state.favorites.add(id)}render();if(state.selectedListing?.id===id)renderDetail(state.selectedListing)}
async function submitListing(e){e.preventDefault();if(!requireAuth())return;if(!db){message("listingMessage","Supabase bağlantısı yapılandırılmamış.",true);return}const btn=$("#listingSubmit");btn.disabled=true;btn.textContent="İlan kaydediliyor...";message("listingMessage","");
  try{let image_url=null;const file=$("#listingImage").files[0];if(file){if(file.size>5*1024*1024)throw Error("Fotoğraf en fazla 5 MB olabilir.");if(!["image/jpeg","image/png","image/webp"].includes(file.type))throw Error("JPG, PNG veya WEBP formatı seç.");const ext=file.name.split(".").pop().toLowerCase();const path=`${state.user.id}/${crypto.randomUUID()}.${ext}`;const {error:upErr}=await db.storage.from("listing-images").upload(path,file,{cacheControl:"3600",upsert:false,contentType:file.type});if(upErr)throw upErr;const {data}=db.storage.from("listing-images").getPublicUrl(path);image_url=data.publicUrl}
    const row={user_id:state.user.id,title:$("#listingTitle").value.trim(),category:$("#listingCategory").value,price:Number($("#listingPrice").value),condition:$("#listingCondition").value,district:$("#listingDistrict").value.trim()||"Eskişehir",description:$("#listingDescription").value.trim(),image_url,instagram:$("#sellerInstagram").value.trim().replace(/^@/,"")||null,whatsapp:$("#sellerWhatsapp").value.trim()||null,status:"pending"};
    const {error}=await db.from("listings").insert(row);if(error)throw error;$("#listingForm").reset();closeModal("postModal");toast("İlanın gönderildi. Yönetici onayından sonra yayınlanacak.");await loadListings();
  }catch(err){message("listingMessage",friendlyError(err.message),true)}finally{btn.disabled=false;btn.textContent="İlanı yayınla"}}
async function openDetail(id){const x=state.listings.find(v=>v.id===id);if(!x)return;state.selectedListing=x;renderDetail(x);showModal("detailModal")}
function renderDetail(x){const instagram=x.instagram?`<a class="btn btn-ghost" target="_blank" rel="noopener" href="https://instagram.com/${encodeURIComponent(x.instagram)}">Instagram'a ulaş ↗</a>`:"";const phone=(x.whatsapp||"").replace(/\D/g,"");const wa=phone?`<a class="btn btn-primary" target="_blank" rel="noopener" href="https://wa.me/${phone}">WhatsApp ↗</a>`:"";$("#detailContent").innerHTML=`<div class="detail-layout"><div class="detail-photo">${x.image_url?`<img src="${esc(x.image_url)}" alt="${esc(x.title)}">`:`<div class="listing-placeholder">${placeholder(x.category)}</div>`}</div><div class="detail-info"><div class="listing-category">${esc(x.category)} · ${esc(x.condition||"İkinci el")}</div><h2 id="detailTitle">${esc(x.title)}</h2><div class="detail-price">${formatPrice(x.price)}</div><div class="listing-meta"><span>⌖ ${esc(x.district||"Eskişehir")}</span><span>${timeAgo(x.created_at)}</span></div><p class="detail-description">${esc(x.description)}</p><div class="seller-line"><span class="seller-dot">${initial(x.profiles?.username)}</span><span>${esc(x.profiles?.username||"ESB Shop üyesi")}</span></div><div class="detail-actions"><button class="btn btn-ghost" data-favorite="${x.id}">${state.favorites.has(x.id)?"♥ Favorilerimde":"♡ Favorilere ekle"}</button>${instagram}${wa}</div><p class="form-note">Ürünü görmeden ödeme yapma. Teslimat ve ödeme koşullarını satıcıyla netleştir.</p></div></div>`}
async function openProfile(){if(!requireAuth())return;showModal("profileModal");$("#profileContent").innerHTML='<p class="muted">Profil yükleniyor...</p>';const {data:mine}=await db.from("listings").select("id,title,price,status,created_at").eq("user_id",state.user.id).order("created_at",{ascending:false});const {data:favs}=await db.from("favorites").select("listing_id,listings(id,title,price,status)").eq("user_id",state.user.id);const p=state.profile||{};$("#profileContent").innerHTML=`<div class="profile-row"><div class="profile-big">${initial(p.username||state.user.email)}</div><div><b>${esc(p.username||"Kullanıcı")}</b><small>${esc(state.user.email)}</small><small>${esc(p.district||"Eskişehir")}</small></div></div><button class="btn btn-ghost full" id="logoutBtn">Çıkış yap</button><div class="profile-section-title">İlanlarım (${(mine||[]).length})</div>${(mine||[]).length?(mine||[]).map(x=>`<div class="profile-list-item"><span><b>${esc(x.title)}</b><br><small>${formatPrice(x.price)} · ${esc(statusText(x.status))}</small></span>${x.status==="pending"?"":`<button data-own-listing="${x.id}">Görüntüle</button>`}</div>`).join(""):'<p class="muted">Henüz ilan eklemedin.</p>'}<div class="profile-section-title">Favorilerim (${(favs||[]).length})</div>${(favs||[]).length?(favs||[]).map(f=>`<div class="profile-list-item"><span>${esc(f.listings?.title||"İlan")}<br><small>${f.listings?formatPrice(f.listings.price):""}</small></span><button data-open-favorite="${f.listing_id}">Aç</button></div>`).join(""):'<p class="muted">Henüz favorin yok.</p>'}${p.role==="admin"?'<div class="profile-section-title">Yönetici</div><button class="btn btn-primary full" id="adminOpen">Yönetici panelini aç</button>':""}`}
function statusText(s){return ({pending:"Onay bekliyor",approved:"Yayında",rejected:"Reddedildi",sold:"Satıldı"})[s]||s}
async function openAdmin(){if(!requireAuth())return;if(state.profile?.role!=="admin"){toast("Bu alan yalnızca yöneticilere açık.");return}$("#profileContent").innerHTML='<p class="muted">İlanlar yükleniyor...</p>';const {data,error}=await db.from("listings").select("*,profiles(username)").in("status",["pending","approved","rejected"]).order("created_at",{ascending:false}).limit(100);if(error){$("#profileContent").innerHTML=`<p class="form-message error">${esc(error.message)}</p>`;return}$("#profileContent").innerHTML=`<div class="profile-row"><div class="profile-big">EB</div><div><b>Yönetici paneli</b><small>Bekleyen ilanları incele ve durumlarını yönet.</small></div></div>${(data||[]).map(x=>`<div class="profile-list-item admin-item"><span><b>${esc(x.title)}</b><br><small>${esc(x.profiles?.username||"Üye")} · ${formatPrice(x.price)} · ${esc(statusText(x.status))}</small></span><span class="admin-buttons">${x.status!=="approved"?`<button data-admin-status="approved" data-admin-id="${x.id}">Onayla</button>`:""}${x.status!=="rejected"?`<button data-admin-status="rejected" data-admin-id="${x.id}">Reddet</button>`:""}<button data-admin-status="sold" data-admin-id="${x.id}">Satıldı</button></span></div>`).join("")||'<p class="muted">İlan bulunamadı.</p>'}<button class="btn btn-ghost full" id="backProfile" style="margin-top:15px">← Profile dön</button>`}
async function adminStatus(id,status){if(state.profile?.role!=="admin")return;const {error}=await db.from("listings").update({status}).eq("id",id);if(error){toast("İlan durumu değiştirilemedi.");return}toast("İlan durumu güncellendi.");await openAdmin();await loadListings()}
function bindEvents(){
  $("#loginOpen").addEventListener("click",()=>openAuth("login"));$("#postOpen").addEventListener("click",()=>{if(requireAuth())showModal("postModal")});$("#heroPost").addEventListener("click",()=>{if(requireAuth())showModal("postModal")});$("#communityPost").addEventListener("click",()=>openAuth("signup"));$("#emptyPost").addEventListener("click",()=>{if(requireAuth())showModal("postModal")});$("#profileOpen").addEventListener("click",openProfile);
  $$("[data-close]").forEach(b=>b.addEventListener("click",()=>closeModal(b.dataset.close)));$$(".modal-backdrop").forEach(m=>m.addEventListener("click",e=>{if(e.target===m)closeModal(m.id)}));document.addEventListener("keydown",e=>{if(e.key==="Escape")$$(".modal-backdrop:not(.hidden)").forEach(m=>closeModal(m.id))});
  $$("[data-auth-mode]").forEach(b=>b.addEventListener("click",()=>{state.authMode=b.dataset.authMode;updateAuthMode()}));$("#authForm").addEventListener("submit",authSubmit);$("#listingForm").addEventListener("submit",submitListing);
  $("#searchInput").addEventListener("input",e=>{state.search=e.target.value;render()});$("#categoryFilter").addEventListener("change",e=>{state.category=e.target.value;render()});$("#sortSelect").addEventListener("change",e=>{state.sort=e.target.value;render()});$("#clearFilters").addEventListener("click",()=>{state.category="";state.search="";$("#searchInput").value="";$("#categoryFilter").value="";render()});
  $$(".category-card").forEach(b=>b.addEventListener("click",()=>{state.category=state.category===b.dataset.category?"":b.dataset.category;$("#categoryFilter").value=state.category;render();$("#listings").scrollIntoView({behavior:"smooth"})}));
  document.addEventListener("click",async e=>{const fav=e.target.closest("[data-favorite]");if(fav){e.stopPropagation();await toggleFavorite(fav.dataset.favorite);return}const card=e.target.closest("[data-open-listing]");if(card){await openDetail(card.dataset.openListing);return}const own=e.target.closest("[data-own-listing]");if(own){closeModal("profileModal");await openDetail(own.dataset.ownListing);return}const f=e.target.closest("[data-open-favorite]");if(f){closeModal("profileModal");await openDetail(f.dataset.openFavorite);return}const adm=e.target.closest("[data-admin-status]");if(adm){await adminStatus(adm.dataset.adminId,adm.dataset.adminStatus);return}if(e.target.id==="logoutBtn"){await db.auth.signOut();closeModal("profileModal");toast("Çıkış yapıldı.");await refreshSession()}if(e.target.id==="adminOpen")await openAdmin();if(e.target.id==="backProfile")await openProfile()});
  $("#footerRules").addEventListener("click",()=>toast("Güvenli alışveriş: Ürünü kontrol et, satıcıyla koşulları netleştir, şüpheli bağlantılara ve ön ödemelere dikkat et."));
}
function render(){const arr=filteredListings();$("#listingGrid").innerHTML=arr.map(x=>`<article class="listing-card" data-open-listing="${x.id}"><div class="listing-image">${x.image_url?`<img src="${esc(x.image_url)}" alt="${esc(x.title)}" loading="lazy">`:`<div class="listing-placeholder">${placeholder(x.category)}</div>`}<span class="condition-tag">${esc(x.condition||"İkinci el")}</span><button class="favorite-btn ${state.favorites.has(x.id)?"favorited":""}" data-favorite="${x.id}" aria-label="Favoriye ekle">${state.favorites.has(x.id)?"♥":"♡"}</button></div><div class="listing-body"><div class="listing-category">${esc(x.category)}</div><h3>${esc(x.title)}</h3><div class="listing-price">${formatPrice(x.price)}</div><div class="listing-meta"><span>⌖ ${esc(x.district||"Eskişehir")}</span><span>${timeAgo(x.created_at)}</span></div><div class="seller-line"><span class="seller-dot">${initial(x.profiles?.username)}</span><span>${esc(x.profiles?.username||"ESB Shop üyesi")}</span></div></div></article>`).join("");$("#emptyState").classList.toggle("hidden",arr.length>0);if(state.listings.length)$("#statusMessage").textContent=arr.length?`${arr.length} ilan listeleniyor`:"Aramana uygun ilan bulunamadı.";$("#statusMessage").classList.toggle("hidden",arr.length>0);$$(".category-card").forEach(c=>c.classList.toggle("selected",c.dataset.category===state.category))}
bindEvents();
if(db){db.auth.onAuthStateChange((_event,session)=>{state.user=session?.user||null;setTimeout(()=>refreshSession(),0)})}
refreshSession();
